#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x2F3 (0x3A3 - 0xB0)
// BlueprintGeneratedClass InventoryTracker.InventoryTracker_C
class UInventoryTracker_C : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xB0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	TMap<int32, int32>                           ItemIds;                                           // 0xB8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                DLCIds;                                            // 0x108(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<int32, int32>                           Newest_Items;                                      // 0x118(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                Newest_DLCs;                                       // 0x168(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ABP_BaseController_C*                  Controller;                                        // 0x178(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_            New_DLC_Items_Received;                            // 0x180(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            New_Items_Received;                                // 0x190(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<struct FST_InventoryTrackingItem>     Inventory;                                         // 0x1A0(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         NewItemsAvailable;                                 // 0x1B0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                        Pad_2C80[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	FMulticastInlineDelegateProperty_            Finished_Loading_Inventory;                        // 0x1B8(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            Opened_Chest_Event;                                // 0x1C8(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<int32>                                Latest_rewards;                                    // 0x1D8(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FST_FilterOptions                     Global_Filter_Options;                             // 0x1E8(0x20)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FST_NewSortOptions                    Global_Sort_Options;                               // 0x208(0x3)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_2C81[0x5];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TMap<class FString, int32>                   EOS_Bundle_to_Item_ID;                             // 0x210(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                        Working_Item_IDs;                                  // 0x260(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                        Working_DLC_IDs;                                   // 0x270(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<enum class E_ChestTypes, int32>         Chest_Count;                                       // 0x280(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	FMulticastInlineDelegateProperty_            Chest_Data_Changed;                                // 0x2D0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                         Has_Skeleton_DLC;                                  // 0x2E0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                        Pad_2C82[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        Event_Chest_Count;                                 // 0x2E4(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<enum class E_ChestTypes, int32>         Chest_Type_To_ID_Mapping;                          // 0x2E8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<int32, enum class E_ChestTypes>         Chest_ID_to_Type_mapping;                          // 0x338(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         Replicated_Latest_Rewards;                         // 0x388(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                        Pad_2C83[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<int32>                                Valid_Item_Ids;                                    // 0x390(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         Disable_Starting_Items;                            // 0x3A0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                         Disable_Level_Items;                               // 0x3A1(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                         Disable_DLC_Items;                                 // 0x3A2(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

	static class UClass* StaticClass();
	static class UInventoryTracker_C* GetDefaultObj();

	void Give_Specific_Level_Items(TArray<int32>& Levels_Gained, TMap<int32, int32> Items_to_add, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, int32 CallFunc_Array_Length_ReturnValue, class FName CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue);
	void Force_Set_Inventory_Item_Amount(int32 Item_Id, int32 Amount, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TMap<int32, int32> K2Node_MakeMap_Map, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, int32 CallFunc_Array_Length_ReturnValue, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, const struct FST_InventoryTrackingItem& K2Node_SetFieldsInStruct_StructOut, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void Create_Validated_Player_Customization(const struct FST_PlayerCustomisation& New_Player_Customization, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue_2, bool CallFunc_Array_Contains_ReturnValue_3, bool CallFunc_Array_Contains_ReturnValue_4, bool CallFunc_Array_Contains_ReturnValue_5, bool CallFunc_Array_Contains_ReturnValue_6, bool CallFunc_Array_Contains_ReturnValue_7, bool CallFunc_Array_Contains_ReturnValue_8, bool CallFunc_Array_Contains_ReturnValue_9, bool CallFunc_Array_Contains_ReturnValue_10, bool CallFunc_Array_Contains_ReturnValue_11, bool CallFunc_Array_Contains_ReturnValue_12, bool CallFunc_Array_Contains_ReturnValue_13, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, const struct FST_PlayerCustomisation& CallFunc_Get_Player_Customization_Customization);
	void Convert_Player_Customizations_To_Item_IDs(TArray<int32>* Current_items, const TArray<int32>& Worn_items, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, const struct FST_PlayerCustomisation& CallFunc_Get_Player_Customization_Customization, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_5, int32 CallFunc_Array_Add_ReturnValue_6, int32 CallFunc_Array_Add_ReturnValue_7, int32 CallFunc_Array_Add_ReturnValue_8, int32 CallFunc_Array_Add_ReturnValue_9, int32 CallFunc_Array_Add_ReturnValue_10, int32 CallFunc_Array_Add_ReturnValue_11, int32 CallFunc_Array_Add_ReturnValue_12, int32 CallFunc_Array_Add_ReturnValue_13);
	void Validate_Items(int32 NewLocalVar_3, int32 NewLocalVar_2, const TArray<int32>& Items_To_Remove, class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, const TArray<float>& Item_ids, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, const struct FST_PlayerCustomisation& CallFunc_Get_Player_Customization_Customization, int32 CallFunc_Array_Add_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, class FName CallFunc_Conv_StringToName_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue_1, const struct FST_Titles& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue_1, const struct FST_HamerSkin& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue_1, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, class UVaRestRequestJSON* CallFunc_ConstructVaRestRequestExt_ReturnValue, class UVaRestJsonObject* CallFunc_ConstructVaRestJsonObject_ReturnValue, TArray<int32>& CallFunc_Convert_Player_Customizations_To_Item_IDs_current_items, int32 CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue_2, class FName CallFunc_Conv_StringToName_ReturnValue_2, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow_2, bool CallFunc_GetDataTableRowFromName_ReturnValue_2, class AEOS_PlayerState_C* K2Node_DynamicCast_AsEOS_Player_State, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Array_Add_ReturnValue_3);
	void Force_Update_Chest_Data(int32 Start_Chest_Count, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Get_Total_Chest_Count_Total_Chest_Count, int32 CallFunc_Get_Total_Chest_Count_Total_Chest_Count_1, bool CallFunc_NotEqual_IntInt_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, int32 CallFunc_Array_Length_ReturnValue, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, enum class E_ChestTypes CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void Add_Rewards_to_Latest_Rewards(TArray<int32>& New_Rewards, const TArray<int32>& Copy_of_Latest, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, int32 Temp_int_Array_Index_Variable, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Reset_Latest_Rewards();
	void Construct_ID_to_Type_Mapping(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<enum class E_ChestTypes>& CallFunc_Map_Keys_Keys, int32 CallFunc_Array_Length_ReturnValue, enum class E_ChestTypes CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void Reward_Items(TArray<int32>& Items, bool Seen, const TArray<float>& Item_ids, class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Get_Item, float CallFunc_Conv_IntToFloat_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class AAlpha_Game_State_C* CallFunc_Current_Alpha_Game_State_AsAlpha_Game_State, bool CallFunc_WithEditor_ReturnValue, bool CallFunc_WithEditor_ReturnValue_1, class AEOS_PlayerState_C* K2Node_DynamicCast_AsEOS_Player_State, bool K2Node_DynamicCast_bSuccess, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue, class AEOS_PlayerState_C* K2Node_DynamicCast_AsEOS_Player_State_1, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_IsDedicatedServer_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, bool CallFunc_BooleanOR_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, class UVaRestRequestJSON* CallFunc_ConstructVaRestRequestExt_ReturnValue, const class FString& CallFunc_EncodeJsonToSingleString_ReturnValue, class UVaRestJsonObject* CallFunc_ConstructVaRestJsonObject_ReturnValue);
	void Reward_Chests(int32 Winner_Amount, int32 Normal_Amount, TArray<int32>& Levels_Gained, TSet<int32> Temp_Local_Rewards, const TArray<int32>& Reward_Ids, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, enum class E_ChestTypes Temp_byte_Variable, int32 CallFunc_Array_Get_Item, int32 CallFunc_Percent_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, enum class E_ChestTypes Temp_byte_Variable_1, int32 Temp_int_Variable, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable_1, bool CallFunc_LessEqual_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, float CallFunc_RandomFloat_ReturnValue, bool CallFunc_Greater_FloatFloat_ReturnValue, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, enum class E_ChestTypes Temp_byte_Variable_2, int32 CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, int32 CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue, enum class E_ChestTypes Temp_byte_Variable_3, int32 CallFunc_Map_Find_Value_3, bool CallFunc_Map_Find_ReturnValue_3, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, int32 CallFunc_Array_Add_ReturnValue_1, int32 CallFunc_Map_Find_Value_4, bool CallFunc_Map_Find_ReturnValue_4, bool CallFunc_LessEqual_IntInt_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_3, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Add_ReturnValue_4, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2);
	void Try_Adding_Chest_Data(int32 Item_Id, int32 Amount);
	void Steam_DLC_Response(class UVaRestRequestJSON* Request, const TArray<int32>& Bundles_to_Give, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue, enum class EVaRestRequestStatus CallFunc_GetStatus_ReturnValue, const class FString& CallFunc_EncodeJsonToSingleString_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class UVaRestJsonObject* CallFunc_GetObjectField_ReturnValue, int32 Temp_int_Array_Index_Variable, TArray<class UVaRestJsonObject*>& CallFunc_GetObjectArrayField_ReturnValue, class UVaRestJsonObject* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_GetIntegerField_ReturnValue, bool CallFunc_GetBoolField_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Construct_Steam_DLC_Request(class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, const class FString& CallFunc_Get_Primary_Account_ID_Account_ID, class UVaRestJsonObject* CallFunc_ConstructVaRestJsonObject_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue_1, class UVaRestRequestJSON* CallFunc_ConstructVaRestRequestExt_ReturnValue);
	void Add_Items_to_inventory_Inverse(TMap<int32, int32> Items_To_Give, bool Sync_With_AWS, bool Unique_Items_Only, bool Skip_Latest_Call, bool Skip_Existing_Check, const TArray<int32>& Given_Items, bool Updated_Chest_Amounts, const TArray<int32>& Cached_Keys, int32 Amount_to_add, int32 Current_Item_ID, bool Found_In_Inventory, TArray<int32>& CallFunc_Map_Keys_Keys, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_2, TArray<int32>& CallFunc_Map_Keys_Keys_1, int32 CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue_1, enum class E_ChestTypes CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, int32 CallFunc_Array_Length_ReturnValue_2, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_2, const class FString& CallFunc_Conv_IntToString_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_3, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue, int32 CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue_4, int32 CallFunc_Array_Add_ReturnValue_1, int32 CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2, const class FString& CallFunc_Conv_IntToString_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, class FName CallFunc_Conv_StringToName_ReturnValue, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_NotEqual_ByteByte_ReturnValue, const struct FDateTime& CallFunc_Now_ReturnValue, int32 CallFunc_Map_Find_Value_3, bool CallFunc_Map_Find_ReturnValue_3, const struct FST_InventoryTrackingItem& K2Node_MakeStruct_ST_InventoryTrackingItem, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_2, const struct FDateTime& CallFunc_Now_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_2, const struct FST_InventoryTrackingItem& K2Node_SetFieldsInStruct_StructOut, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Add_IntInt_ReturnValue_3);
	void Grant_Base_Items(TMap<int32, int32> Starting_Items, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, int32 CallFunc_Array_Length_ReturnValue, class FName CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue);
	void Give_EOS_Bundles(TArray<class FString>& EOS_Bundles, const TArray<int32>& Bundles_to_Give, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, class FName CallFunc_Array_Get_Item, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Give_Level_and_Base_Items(bool Force_Add_To_Rewards, bool Ignore_Starting_Items, TMap<int32, int32> Items_to_add, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_2, int32 Temp_int_Variable, bool CallFunc_Not_PreBool_ReturnValue_3, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, class UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, class FName CallFunc_Array_Get_Item, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const class FString& CallFunc_Conv_NameToString_ReturnValue, int32 CallFunc_Conv_StringToInt_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class ABP_BaseController_C* K2Node_DynamicCast_AsBP_Base_Controller, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_3);
	void Get_Filtered_Sorted_Inventory_Global_Category(enum class E_SteamItemCategories Category, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& LocalFilteredInventory, bool NewLocalVar_1, bool NewLocalVar_0, const TArray<int32>& ItemDefs, const TArray<struct FST_InventoryTrackingItem>& LocalSortedInventory, const struct FST_FilterOptions& K2Node_MakeStruct_ST_FilterOptions, TArray<struct FST_InventoryTrackingItem>& CallFunc_Get_Filtered_Sorted_Inventory_Sorted_Inventory);
	void Get_Filtered_Sorted_Inventory_Global(TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& LocalFilteredInventory, bool NewLocalVar_1, bool NewLocalVar_0, const TArray<int32>& ItemDefs, const TArray<struct FST_InventoryTrackingItem>& LocalSortedInventory, TArray<struct FST_InventoryTrackingItem>& CallFunc_Get_Filtered_Sorted_Inventory_Sorted_Inventory);
	void Sort_Event(TArray<struct FST_InventoryTrackingItem>& Input_Inventory, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& Output_Inventory, const TArray<int32>& Events, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Array_Get_Item_2, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Array_AddUnique_ReturnValue);
	void Sort_Rarity(TArray<struct FST_InventoryTrackingItem>& Input_Inventory, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& Output_Inventory, const TArray<int32>& Qualities, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Array_Get_Item_2, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Array_AddUnique_ReturnValue);
	void Sort_Last_Added(TArray<struct FST_InventoryTrackingItem>& Input_Inventory, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& Output_Inventory, const TArray<struct FDateTime>& Dates, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_2, int32 Temp_int_Loop_Counter_Variable_1, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, const struct FDateTime& CallFunc_Array_Get_Item_2, bool CallFunc_EqualEqual_DateTimeDateTime_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Array_AddUnique_ReturnValue);
	void Sort_Alphabetically(TArray<struct FST_InventoryTrackingItem>& Input_Inventory, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& Output_Inventory, const TArray<class FString>& Names, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, int32 Temp_int_Loop_Counter_Variable_2, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, const class FString& CallFunc_Array_Get_Item_2, bool CallFunc_EqualEqual_StrStr_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_2, bool CallFunc_Less_IntInt_ReturnValue_2, int32 CallFunc_Array_AddUnique_ReturnValue);
	void Get_Sorted_Inventory(TArray<struct FST_InventoryTrackingItem>& Local_Inventory, struct FST_NewSortOptions& Sort_Options, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<class ABP_Controller_C*>& Test_Array, const TArray<struct FST_InventoryTrackingItem>& Local_Sorted_Inventory, TArray<struct FST_InventoryTrackingItem>& CallFunc_Sort_Rarity_Sorted_Inventory, bool K2Node_SwitchEnum_CmpSuccess, TArray<struct FST_InventoryTrackingItem>& CallFunc_Sort_Last_Added_Sorted_Inventory, TArray<struct FST_InventoryTrackingItem>& CallFunc_Sort_Alphabetically_Sorted_Inventory, TArray<struct FST_InventoryTrackingItem>& CallFunc_Sort_Event_Sorted_Inventory);
	void Get_Filtered_Inventory(TArray<struct FST_InventoryTrackingItem>& Local_Inventory, struct FST_FilterOptions& ST_FilterOptions, TArray<struct FST_InventoryTrackingItem>* Filtered_Inventory, const TArray<struct FST_InventoryTrackingItem>& Local_Filtered_Inventory, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void Get_Filtered_Sorted_Inventory(const struct FST_FilterOptions& Filter_Options, const struct FST_NewSortOptions& Sort_Options, TArray<struct FST_InventoryTrackingItem>* Sorted_Inventory, const TArray<struct FST_InventoryTrackingItem>& LocalFilteredInventory, bool NewLocalVar_1, bool NewLocalVar_0, const TArray<int32>& ItemDefs, const TArray<struct FST_InventoryTrackingItem>& LocalSortedInventory, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, TArray<struct FST_InventoryTrackingItem>& CallFunc_Get_Filtered_Inventory_Filtered_Inventory, TArray<struct FST_InventoryTrackingItem>& CallFunc_Get_Sorted_Inventory_Sorted_Inventory);
	void Condense_Items(TArray<int32>& Items, TMap<int32, int32>* Condensed_Items, TMap<int32, int32> Temp_Condensed_Items, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1);
	void Remove_Items_From_Inventory(int32 Item_Id, int32 Amount, bool Updated_Chest_Amounts, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, enum class E_ChestTypes CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, int32 CallFunc_Array_Length_ReturnValue, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, const struct FST_InventoryTrackingItem& K2Node_SetFieldsInStruct_StructOut);
	void Get_Total_Chest_Count(int32* Total_Chest_Count, int32 Total_Count, int32 CallFunc_MakeLiteralInt_ReturnValue, int32 Temp_int_Variable, int32 Temp_int_Variable_1, uint8 CallFunc_Conv_IntToByte_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, uint8 CallFunc_GetValidValue_ReturnValue, uint8 CallFunc_Conv_IntToByte_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, uint8 CallFunc_GetEnumeratorValueFromIndex_ReturnValue, int32 CallFunc_Conv_ByteToInt_ReturnValue, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1);
	void Sync_Inventory_with_AWS();
	void Check_For_New_Items(TMap<int32, int32> Found_Items, bool Found_In_current_Inventory, TMap<int32, int32> New_Items_To_Give, int32 Temp_int_Loop_Counter_Variable, TArray<int32>& CallFunc_Map_Keys_Keys, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Get_Item, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable_1, const struct FST_InventoryTrackingItem& CallFunc_Array_Get_Item_1, bool CallFunc_EqualEqual_IntInt_ReturnValue, int32 CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void Process_AWS_Items(class UVaRestRequestJSON* Request, int32 Page, const TArray<int32>& Aditional_Bundles_To_Give, const TArray<int32>& Amounts, const TArray<int32>& Item_Ids, bool Updated_Chest_Amounts, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue, int32 CallFunc_GetIntegerField_ReturnValue, TArray<int32>& CallFunc_GetIntegerArrayField_ReturnValue, TArray<int32>& CallFunc_GetIntegerArrayField_ReturnValue_1, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, bool CallFunc_Greater_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Get_Item, bool CallFunc_Greater_IntInt_ReturnValue_1, int32 CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue, enum class E_ChestTypes CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const class FString& CallFunc_Conv_IntToString_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, const struct FST_InventoryTrackingItem& K2Node_MakeStruct_ST_InventoryTrackingItem, int32 CallFunc_Array_Add_ReturnValue_1, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, const class FString& CallFunc_Get_Primary_Platform_Custom_Primary_Platform, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_EqualEqual_StrStr_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void Retrieve_item_list_from_AWS(int32 Start_Item_Id, const class FString& Url_Extension, class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, const class FString& CallFunc_Conv_IntToString_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, class AEOS_PlayerState_C* K2Node_DynamicCast_AsEOS_Player_State, bool K2Node_DynamicCast_bSuccess, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, class UVaRestRequestJSON* CallFunc_ConstructVaRestRequestExt_ReturnValue, class UVaRestJsonObject* CallFunc_ConstructVaRestJsonObject_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, const class FString& CallFunc_Get_Primary_Account_ID_Account_ID, const class FString& CallFunc_Concat_StrStr_ReturnValue_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_IsEmpty_ReturnValue);
	void Give_Bundles(TArray<int32>& Bundle_ID, TMap<int32, int32> Items_to_add, const TArray<enum class E_EventDLCBundle>& Bundles_To_Enable, const TArray<class FString>& Bundle_Names, class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Get_Item, const class FString& CallFunc_Conv_IntToString_ReturnValue, class FName CallFunc_Conv_StringToName_ReturnValue, int32 Temp_int_Loop_Counter_Variable, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, enum class E_EventDLCBundle Temp_byte_Variable, int32 Temp_int_Variable, bool CallFunc_Array_Contains_ReturnValue, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, int32 CallFunc_Array_Length_ReturnValue_2, class FName CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, const struct FST_NewEOSInventoryItem& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, const class FString& CallFunc_Conv_NameToString_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, int32 CallFunc_Conv_StringToInt_ReturnValue);
	void Open_Chest(enum class E_ChestTypes Chest_Item_ID, int32 Chest_Item_Count, bool TestMode, class UVaRestRequestJSON* Json_Request, class UVaRestJsonObject* Json_Object, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, const class FString& CallFunc_Get_Primary_Account_ID_Account_ID, int32 CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UVaRestSubsystem* CallFunc_GetEngineSubsystem_ReturnValue, class UVaRestRequestJSON* CallFunc_ConstructVaRestRequestExt_ReturnValue, class UVaRestJsonObject* CallFunc_ConstructVaRestJsonObject_ReturnValue);
	void Received_Bundle(class UVaRestRequestJSON* Request);
	void Received_Rewards(class UVaRestRequestJSON* Request);
	void Opened_Chest_Response(class UVaRestRequestJSON* Request);
	void Validated_Items(class UVaRestRequestJSON* Request);
	void OC_Show_Rewards(TArray<int32>& Received_Rewards);
	void Initialize();
	void ReceiveBeginPlay();
	void Refresh_Inventory();
	void ExecuteUbergraph_InventoryTracker(int32 EntryPoint, class UEOS_GameInstance_C* CallFunc_Current_Game_EOS_Instance_AsEOS_Game_Instance, class UVaRestRequestJSON* K2Node_CustomEvent_Request_3, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue, const class FString& CallFunc_EncodeJsonToSingleString_ReturnValue, class UVaRestJsonObject* CallFunc_GetObjectField_ReturnValue, int32 CallFunc_GetIntegerField_ReturnValue, TArray<int32>& CallFunc_GetIntegerArrayField_ReturnValue, enum class EVaRestRequestStatus CallFunc_GetStatus_ReturnValue, TMap<int32, int32> CallFunc_Condense_Items_condensed_Items, bool CallFunc_EqualEqual_ByteByte_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, TArray<int32>& K2Node_MakeArray_Array, class UVaRestRequestJSON* K2Node_CustomEvent_Request_2, TMap<int32, int32> CallFunc_Condense_Items_condensed_Items_1, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue_1, class UVaRestJsonObject* CallFunc_GetObjectField_ReturnValue_1, enum class EVaRestRequestStatus CallFunc_GetStatus_ReturnValue_1, bool CallFunc_GetBoolField_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, class UVaRestRequestJSON* K2Node_CustomEvent_Request_1, class UVaRestRequestJSON* K2Node_CustomEvent_Request, class UVaRestJsonObject* CallFunc_Get_Data_From_Response_Response_Data, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue_2, int32 CallFunc_GetIntegerField_ReturnValue_1, bool CallFunc_GetBoolField_ReturnValue_1, int32 CallFunc_GetIntegerField_ReturnValue_2, enum class E_ChestTypes CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, TArray<int32>& CallFunc_GetIntegerArrayField_ReturnValue_1, TMap<int32, int32> CallFunc_Condense_Items_condensed_Items_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Greater_IntInt_ReturnValue_1, enum class EVaRestRequestStatus CallFunc_GetStatus_ReturnValue_2, enum class EVaRestRequestStatus CallFunc_GetStatus_ReturnValue_3, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, class UVaRestJsonObject* CallFunc_GetResponseObject_ReturnValue_3, const class FString& CallFunc_GetStringField_ReturnValue, class UGameInstance* CallFunc_GetGameInstance_ReturnValue, class UBP_GameInstance_C* K2Node_DynamicCast_AsBP_Game_Instance, bool K2Node_DynamicCast_bSuccess, TArray<int32>& K2Node_CustomEvent_Received_Rewards, const struct FST_PlayerCustomisation& CallFunc_Get_Player_Customization_Customization, const struct FST_PlayerCustomisation& K2Node_SetFieldsInStruct_StructOut, class AActor* CallFunc_GetOwner_ReturnValue, class ABP_BaseController_C* K2Node_DynamicCast_AsBP_Base_Controller, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_IsLocalPlayerController_ReturnValue);
	void Chest_Data_Changed__DelegateSignature();
	void Opened_Chest_Event__DelegateSignature(bool Successful, TArray<int32>& Items, const class FString& Message);
	void Finished_Loading_Inventory__DelegateSignature();
	void New_Items_Received__DelegateSignature(TArray<int32>& Items);
	void New_DLC_Items_Received__DelegateSignature(int32 bundle_id, TArray<int32>& Items);
};

}


